EDX-4239 Add partial go-mod-bootstrap code
IOTechSystems/go-mod-edge-utils pull request #4
Opened 2023-09-14 05:55 UTC by jinlinGuan

2023-09-20 10:13 UTC, cloudxxx8 requested changes

2023-09-20 10:15 UTC, cloudxxx8 requested changes

2023-09-20 10:15 UTC, cloudxxx8 commented on pkg/di/container.go
> +	c.mutex.Lock()
Get should be `Rlock()`

2023-09-20 10:58 UTC, cloudxxx8 requested changes

2023-09-20 10:58 UTC, cloudxxx8 commented on pkg/di/type.go
rename to helper.go, because it doesn't contain any type.

2023-09-20 14:00 UTC, cloudxxx8 requested changes

2023-09-20 14:00 UTC, cloudxxx8 commented on pkg/secrets/types/config.go
remove this file and package
we don't use it for now

2023-09-20 14:00 UTC, cloudxxx8 commented on pkg/bootstrap/config/types.go
> +	RuntimeTokenProvider types.RuntimeTokenProviderInfo
remove RuntimeTokenProvider

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/bootstrap/flags/flags.go
> +			"    -cf, --configFile <name>        Indicates name of the local configuration file. Defaults to configuration.toml\n"+
updated

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/bootstrap/bootstrap.go
> +	lc := container.LoggingClientFrom(dic.Get)
renamed

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/logger/logger.go
> +type LoggingClient interface {
renamed

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/logger/logger.go
>  type Logger struct {
renamed

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/bootstrap/config/types.go
> +func NewSecretStoreInfo(serviceKey string) SecretStoreInfo {
removed

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/bootstrap/configprocessor/processor.go
> +	cp.lc.Info(fmt.Sprintf("Loaded %s configuration from %s", configType, filePath))
updated

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/bootstrap/configprocessor/processor.go
> +	}
added

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/bootstrap/configprocessor/processor.go
> +func getSecretNamesChanged(prevVals config.InsecureSecrets, curVals config.InsecureSecrets) []string {
removed

2023-09-21 08:45 UTC, jinlinGuan commented on pkg/di/container.go
> +	c.mutex.Lock()
updated

2023-09-21 08:46 UTC, jinlinGuan commented on pkg/di/type.go
renamed

2023-09-21 08:46 UTC, jinlinGuan commented on pkg/secrets/types/config.go
removed

2023-09-21 08:46 UTC, jinlinGuan commented on pkg/bootstrap/config/types.go
> +	RuntimeTokenProvider types.RuntimeTokenProviderInfo
removed

2023-09-21 08:46 UTC, jinlinGuan commented on pkg/bootstrap/container/logger.go
> +func LoggingClientFrom(get di.Get) logger.LoggingClient {
renamed

2023-09-23 09:20 UTC, cloudxxx8 requested changes

2023-09-23 09:20 UTC, cloudxxx8 commented on pkg/bootstrap/handlers/message.go
> +	logger.Info(fmt.Sprintf("Starting %s %s ", h.serviceKey, h.version))
```suggestion
	logger.Infof("Starting %s %s ", h.serviceKey, h.version)
```

2023-09-23 09:36 UTC, cloudxxx8 commented on go.mod
> +	github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
we need to add metrics related code back to this repository in the next PR

2023-09-25 03:06 UTC, cloudxxx8 approved these changes
LGTM

2023-09-25 03:06 UTC, merged